/*
 * Created on 17 Dec 2018 ( Time 16:17:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.fileService.service;

import com.core.entity.VbAttachment;


/**
 * Business Service Interface for entity VbAttachment.
 */
public interface VbAttachmentService {

    VbAttachment findById(Long id);

    VbAttachment findByObjectId(Long id);
    
    VbAttachment save(VbAttachment vbAttachment);
    
    //VbAttachment findOriginByObjectId(String id);

//    List<VbAttachment> updateDocAttachmentInfo(List<String> attachIds, String objectId, Long objectType);

}
