/*
 * Created on 17 Dec 2018 ( Time 16:17:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.core.entity;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "VB_ATTACHMENT"
 *
 * @author Telosys Tools Generator
 */
@Entity
@Table(name = "ATTACH_DOCUMENT")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter

public class AttachDocument extends Auditable<String> implements Serializable {

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ATTACH_DOCUMENT_ID", nullable = false)
    private Long attachDocumentId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FILE_NAME")
    private String fileName;

    @Column(name = "FILE_CODE", length = 150)
    private String fileCode;

    @Column(name = "FILE_TYPE", length = 50)
    private String fileType;

    @Column(name = "FILE_SIZE", length = 1000)
    private Long fileSize;

    @Column(name = "IS_ENCRYPT")
    private Long isEncrypt;

    @Column(name = "IS_PDF")
    private Long isPdf;

    @Column(name = "PDF_ATTACH_DOCUMENT_ID")
    private String pdfAttachmentDocumentId;

    @Column(name = "IS_ORIGINAL")
    private Long isOriginal;

    @Column(name = "DESCRIPTION")
    private String description;

    @Column(name = "FILE_PATH", length = 500)
    private String filePath;

    @Column(name = "CONTENT_TYPE", length = 100)
    private String contentType;

    @Column(name = "IS_DELETE", columnDefinition = "bigint default 0")
    private Long isDelete = 0L;

    @Column(name = "CREATOR_ID")
    private Long creatorId;

    @Column(name = "UPDATOR_ID")
    private Long updatorId;

}
